finalproject_v2/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('motels.urls')),
    path('finance/', include('finance.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finance/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_form, name="view_form"),
    path('your_finance/', views.your_finance, name="your_finance"),
    # Api
    path('api/callback', views.callback, name="callback"),
]

motels/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('', views.index, name="index"),
    path('register', views.register, name="register"),
    path('admin_login', LoginView.as_view(), name='admin_login'),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
    path('<str:user_name>', views.profile, name="profile"),
    path('create_post/category', views.create_post_category, name='create_post_category'),
    path('create_post/new', views.create_post_new, name='create_post_new'),
    path('create_post/new/action', views.create_post_new_action, name='create_post_new_action'),
    path('<str:user_name>/posts/<str:title>', views.view_own_post, name='view_own_post'),
    path('<str:user_name>/saved', views.post_saved, name='post_saved'),
    path('user/password_change/', views.user_change_password, name='user_change_password'),
    path('user/edit/', views.user_edit, name='user_edit'),
    path('<int:post_id>/change/', views.change_post, name='change_post'),
    # API route
    path('api/edit_profile', views.edit_profile, name="edit_profile"),
    path('api/save_profile', views.save_profile, name='save_profile'),
    path('api/get_district/<str:province_id>', views.get_district, name='get_district'),
    path('api/get_commune/<str:district_id>', views.get_commune, name='get_commune'),
    path('api/get_index', views.get_index, name='get_index'),
    path('api/follow', views.follow, name="follow"),
    path('<int:user_id>/post/<str:section>/', views.profile_get_post, name='profile_get_post'),
    # socket route
#     path(
#     'admin/password_reset/done/',
#     auth_views.PasswordResetDoneView.as_view(),
#     name='password_reset_done',
# ),
]

finance/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone
# Create your models here.
import motels
from motels.models import User, Post

from motels import util

class CardType(models.Model):
    code = models.CharField(max_length=20, verbose_name='Code')
    name = models.CharField(max_length=20, verbose_name='Telecom')
    class Meta:
        verbose_name = 'Telecom'
        verbose_name_plural = 'Telecom'

    def __str__(self):
        return self.name

class CardAmount(models.Model):
    amount = models.IntegerField(validators=[MinValueValidator(10000)], verbose_name='Amount')
    # class Meta:
    #     verbose_name = 'Mệnh giá'
    #     verbose_name_plural = 'Mệnh giá'

    def __str__(self):
        return str(self.amount)


class CardHistory(models.Model):
    status = models.IntegerField(default=99)
    message = models.CharField(max_length=50)
    request_id = models.CharField(max_length=69, verbose_name='Request id')
    value = models.IntegerField(null=True, verbose_name='Value')
    amount = models.IntegerField(null=True, verbose_name='Return Value')

    code = models.CharField(max_length=50)
    serial = models.CharField(max_length=50)
    trans_id = models.CharField(null=True, max_length=100, blank=True)
    callback_sign = models.CharField(max_length=200, blank=True)
    timestamp = models.DateTimeField(verbose_name='Time', auto_now_add=True)
    declared_value = models.ForeignKey(CardAmount, verbose_name='Declared value ', related_name='price', on_delete=models.CASCADE)
    telco = models.ForeignKey(CardType, verbose_name='Telecom', related_name='type', on_delete=models.CASCADE)
    user = models.ForeignKey(motels.models.User, related_name='cards', verbose_name='User', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'History'
        verbose_name_plural = 'History'

    def __str__(self):
        return f"{self.request_id} - {self.value} - {self.telco}"

    def get_date(self):
        return util.get_date(self, self.timestamp)

    def is_waiting(self):
        if self.status == 99:
            return True
        return False

    def is_success(self):
        if self.status == 1 or self.status == 2:
            return True
        return False
        
    def is_fail(self):
        if self.status == 3:
            return True
        return False

    def get_status(self):
        if self.status == 99:
            return 'Chờ xử lý'
        if self.status == 1 or self.status == 2:
            return 'Thành công'
        if self.status == 3:
            return 'Thất bại'

    get_date.short_description = 'Time'

class Vip(models.Model):
    amount = models.IntegerField(validators=[MinValueValidator(1000)], unique=True, verbose_name='Amount/day',  help_text='<span style="position:absolute;left:205px; top:17px ">VND</span>')
    timestamp = models.DateTimeField(verbose_name='Thời gian tạo', auto_now_add=True)
    
    class Meta:
        verbose_name = 'Vip'
        verbose_name_plural = 'Vip'
    def __str__(self):
        return f'{self.amount}/day'
    
class Discount(models.Model):
    timestamp = models.DateTimeField(verbose_name='Thời gian tạo', auto_now_add=True)
    percent = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    day = models.IntegerField(verbose_name='Số ngày', validators=[MinValueValidator(1)])
    amount= models.ManyToManyField(Vip, blank=True, through='VipDiscount')

    class Meta:
        verbose_name = 'Discount'
        verbose_name_plural = 'Discount'

class VipDiscount(models.Model):
    vip = models.ForeignKey(Vip, on_delete=models.CASCADE)
    discount = models.ForeignKey(Discount, on_delete=models.CASCADE) 
    is_active = models.BooleanField(verbose_name='Hiệu lực')

class PostedAds(models.Model):
    timestamp = models.DateTimeField(verbose_name='Thời gian đẩy', auto_now_add=True)
    days = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(30)], verbose_name='Số ngày chạy')
    vip_discount = models.ForeignKey(VipDiscount, verbose_name='Mã giảm giá', on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(Post, related_name='ads', verbose_name='Bài đăng', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Ads'
        verbose_name_plural = 'Ads'

    def get_how_long(self):
        return util.get_how_long(self, self.timestamp)

finance/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.contrib import messages

from .models import CardHistory, CardAmount, CardType

class RechargeForm(forms.ModelForm):
    telco = forms.ModelChoiceField(label='Nhà mạng', queryset=CardType.objects.all(), widget=forms.RadioSelect, empty_label=None)
    declared_value = forms.ModelChoiceField(label='Mệnh giá', queryset=CardAmount.objects.all(), empty_label='Mệnh giá')

    class Meta:
        model = CardHistory
        fields = ('serial', 'telco', 'declared_value', 'code')

    def clean(self):
        if self.is_valid():
            code = self.cleaned_data['code']  
            serial = self.cleaned_data['serial']
            telco = self.cleaned_data['telco']
            his = CardHistory.objects.filter(code=code).filter(serial=serial).filter(telco=telco)
            if len(his) != 0:
                his = his.first()
                if his.status == 99:
                    raise forms.ValidationError("Thẻ này đã được yêu cầu và đang chờ được xử lý")
                if his.status == 1 or  his.status == 2 or  his.status == 3:
                    raise forms.ValidationError("Thẻ này đã được sử dụng, vui lòng chọn thẻ khác")
        # raise forms.ValidationError("Vui lòng nhập đủ tất cả các trường")

            

            
        

finance/views.py
import json, random, hashlib, urllib.parse, requests, pycurl, certifi
from io import StringIO 
from django.utils import timezone
from django.urls import reverse
# from cStringIO import StringIO

from django.http import JsonResponse, Http404
from django.db.models import Q, Sum
from django.shortcuts import render
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import HttpResponseRedirect, HttpResponse, redirect
from .forms import RechargeForm
from .models import CardType, CardAmount, CardHistory
from django.contrib.messages import constants as message_constants
from django.contrib import messages

# Create your views here.


@login_required
def view_form(request):
    his = CardHistory.objects.select_related('user').filter(user=request.user).order_by('-id')
    finance = CardHistory.objects.select_related('user').filter(user=request.user).filter(Q(status=1)|Q(status=2)).aggregate(Sum('value'))
    if request.method == 'GET':     
        form = RechargeForm()

    if request.method == 'POST':
        form = RechargeForm(request.POST)
        if form.is_valid():
            request_id = random.randrange(100004, 99999999)
            request_id = str(request_id)
            command = 'charging'
            url = "https://thesieure.com/chargingws/v2"
            partner_id = '7833818951'
            partner_key = 'f823c010fc2e43f442a82257bb5a023d'

            code = request.POST['code'].strip()
            serial = request.POST['serial'].strip()
            declared_value = int(request.POST['declared_value'])
            telco = int(request.POST['telco'])

            if not code or not serial:
                return HttpResponse('Code và serial không được bỏ trống')
                
            try:
                telco_value = CardType.objects.get(pk=request.POST['telco']).code 
            except IntegrityError: 
                raise Http404("Loại nhà mạng này không tồn tại")

            try:
                declared_value_value = str(CardAmount.objects.get(pk=request.POST['declared_value']).amount)
            except IntegrityError: 
                raise Http404("Mệnh giá này không tồn tại")
                
            string = partner_key + code + command + partner_id + request_id + serial + telco_value
            sign = hashlib.md5(string.encode()).hexdigest()

            dataPost = dict()
            dataPost['request_id'] = request_id
            dataPost['code'] = code
            dataPost['partner_id'] = partner_id
            dataPost['serial'] = serial
            dataPost['telco'] = telco_value
            dataPost['command'] = command
            dataPost['amount'] = declared_value_value
            dataPost['sign'] = sign
            # data = urllib.parse.urlencode(dataPost)
            
            data = json.dumps(dataPost)

            len_data = len(data)
            data = StringIO(data)
            ch = pycurl.Curl()
            
            ch.setopt(pycurl.CAINFO, certifi.where())
            ch.setopt(pycurl.URL, url)
            ch.setopt(pycurl.HTTPHEADER, ['Accept: application/json',
                                'Content-Type: application/json'])
            ch.setopt(pycurl.POST, 1)
            ch.setopt(pycurl.READDATA, data)
            ch.setopt(pycurl.POSTFIELDSIZE, len_data)
            ch.perform()

            status_code = ch.getinfo(pycurl.RESPONSE_CODE)
            if status_code != 200:
                print('Aww Snap :( Server returned HTTP status code {}'.format(status_code))
            ch.close()

            callbackstring = partner_key + code + serial
            callback_sign = hashlib.md5(callbackstring.encode()).hexdigest()
            his = CardHistory(message='Thẻ chờ xử lý', request_id=request_id, value=None, amount=None, code=code, serial=serial, \
                trans_id=None, callback_sign=callback_sign, declared_value=CardAmount.objects.get(pk=declared_value), telco=CardType.objects.get(pk=telco), user=request.user)
            his.save()

            messages.add_message(
                request, messages.SUCCESS, 'Thẻ đang chờ xử lý',
                fail_silently=True,
            )
            return HttpResponseRedirect(reverse("view_form"))
    context = { 
        'form': form, 
        'finance': finance['value__sum'] or 0,
        'his': his 
        }
    return render(request, 'finance/view_form.html', context)

@csrf_exempt
def callback(request):
    if request.method == 'POST': 
        data = json.loads(request.body)

        code = data.get('code')
        serial = data.get('serial')
        partner_key = 'f823c010fc2e43f442a82257bb5a023d'

        telco = CardType.objects.filter(code=data.get('telco')).first()
        try:
            his = CardHistory.objects.filter(code=code).filter(serial=serial).filter(telco=telco).first()
            if his.callback_sign == data.get('callback_sign'):
                his.request_id = data.get('request_id')
                his.message = data.get('message')
                his.status = int(data.get('status'))
                his.value = int(data.get('value'))
                his.amount = int(data.get('amount'))
                his.trans_id = data.get('trans_id')
                his.callback_sign = data.get('callback_sign')
                his.timestamp = timezone.now()
                his.save()
            else:
                return HttpResponse('sai hash')
        except IntegrityError:
            raise Http404('Bản ghi không tồn tại')
        return HttpResponse(serial)
    return HttpResponse('ghcvhgd')

@login_required
def your_finance(request):
    
    u = request.user
    finance = CardHistory.objects.select_related('user').filter(user=u).filter(Q(status=1)|Q(status=2)).aggregate(Sum('value'))
    his = CardHistory.objects.select_related('user').filter(user=request.user).order_by('-id')
    context = {
        'his': his,
        'finance': finance['value__sum'] or 0
    }
    return render(request, 'finance/your_finance.html', context)

templates/finance/view_form.html
{% extends 'motels/base.html' %}

{% load static %}

{% block body %}
<div class=" px-3">
    <div class="create_post pt-4 px-5 pb-3 profile-grid-item">
        <div class="box shadow-sm px-4 py-4">
            <div id="finance_now">Bạn đang có <span>{{ finance }}</span> đ</div>
        </div>
    </div>
</div>
<div class="finance px-3">
    <div class="create_post pl-5 pt-2 pr-2 pb-3 profile-grid-item">
        <div class="box shadow-sm px-4 py-4">
            <div class='finance-form-button'>
                <button>MUA MÃ THẺ</button>
            </div>
            
            <form action="" method="POST"  autocomplete="off">
                {% csrf_token %}
                {% load crispy_forms_tags %}
                <div class="mb-4">
                    <p class="pb-4">CHỌN LOẠI NHÀ MẠNG</p>
                    <div class="form-group">
                        <div class="">
                            {% for type in form.telco %}
                                {{ type }}
                            {% endfor %}
                        </div>
                    </div>
                </div>
                
                <div class="mb-4">
                    <p class="pb-4">NHẬP THÔNG TIN THẺ CÀO</p>
                    <div class="form-group row">
                        <label for="" class="col-sm-3 col-form-label">{{ form.code.label_tag }}</label>
                        <div class="col-sm-9 ">
                            {{form.code}}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="" class="col-sm-3 col-form-label">{{ form.serial.label_tag }}</label>
                        <div class="col-sm-9 ">
                            {{form.serial}}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-form-label col-sm-3 pt-0">{{ form.declared_value.label_tag  }}</label>
                        <div class="col-sm-9">
                            {{form.declared_value}}
                        </div>
                        
                    </div>
                </div>
                
                {{ form|as_crispy_errors }}
                  
               
                <div class='finance-form-button'>
                    <input type="submit" id="button_post" value="Nạp">
                </div>
            </form>
        </div>
    </div>
    <div class=" pl-1 pt-2 pr-5 pb-3 profile-grid-item">
        <div class="box shadow-sm px-4 py-4">

            <p class="create_post_head pb-4">Lịch sử nạp thẻ</p>
            {% if his %}
            <table id="history">
                <tr>
                    <th>Trạng thái</th>
                    <th>Mã code</th>
                    <th>Seri</th>
                    <th>Nhà mạng</th>
                    <th>Khai</th>
                    <th>Thực</th>
                    <th>Nhận</th>
                    <th>Ngày</th>
                    <th>Mã giao dịch</th>
                </tr>
                {% for h in his %}
                    <tr>
                        <td>
                            <span {{ h.is_waiting|yesno:' class=is_waiting,' }} {{ h.is_success|yesno:' class=is_success,' }} {{ h.is_fail|yesno:' class=is_fail,' }}>{{ h.get_status }}</span>
                        </td>
                        <td>{{ h.code }}</td>
                        <td>{{ h.serial }}</td>
                        <td>{{ h.telco }}</td>
                        <td class="finance_vnd">{{ h.declared_value }}</td> 
                        <td class="finance_vnd">{{ h.value }}</td>
                        <td class="finance_vnd">{{ h.amount }}</td>
                        <td>{{ h.get_date }}</td>
                        <td>{{ h.request_id }}</td>
                    </tr>
                {% empty %}
                {% endfor %}
            </table>
            {% else %}
            Bạn chưa có giao dịch nào
            {%  endif %}
        </div>
    </div>
</div>
<!--  -->

<!--  -->

{% if messages %}
<div class="message">
    {% for message in messages %}
    <p>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </p>
    {% endfor %}
</ul>
{% endif %}
<script>
    document.addEventListener('DOMContentLoaded', () => {
        document.querySelectorAll('#id_declared_value option').forEach(item => {
            if (item.index != 0) {
                convert(item.innerHTML, item);
            }
        })
    })

    function convert(amount, item) {
        let modun = parseInt(amount.length/3);
        let len = amount.length;
        let arr = new Array();
        for (let i = modun; i >= 0; i--) {
            arr[i] = ',' + amount.slice((len - (modun + 1-i)*3), (len-(modun-i)*3));
            if (i === 0) {
                arr[i] = amount.slice(0, len-modun*3);
            }
        } 
        let str = arr.toString();
        let str2 = str.replace(/,,/g,",");
        if (str2[0] === ',') {
            str2 = str2.slice(1, str2.length);
            item.innerHTML = str2;
        }
        else {
            item.innerHTML = str2;
        }
    }
</script>
<script>
    document.addEventListener('DOMContentLoaded', () => {
        convert(document.querySelector('#finance_now span').innerHTML, document.querySelector('#finance_now span'));
        document.querySelectorAll('.finance_vnd').forEach(td => {
            convert(td.innerHTML, td);
        })
    })

    function convert(amount, item) {
        let modun = parseInt(amount.length/3);
        let len = amount.length;
        let arr = new Array();
        for (let i = modun; i >= 0; i--) {
            arr[i] = ',' + amount.slice((len - (modun + 1-i)*3), (len-(modun-i)*3));
            if (i === 0) {
                arr[i] = amount.slice(0, len-modun*3);
            }
        } 
        let str = arr.toString();
        let str2 = str.replace(/,,/g,",");
        if (str2[0] === ',') {
            str2 = str2.slice(1, str2.length);
            item.innerHTML = str2;
        }
        else {
            item.innerHTML = str2;
        }
    }
</script>
{% endblock %}

templates/finance/your_finance.html
{% extends 'motels/base.html' %}

{% load static %}

{% block body %}

<div class="profile px-3">
    <div class="profile-grid-item pl-5 pt-4 pr-2 pb-3">
        <div class="box shadow-sm px-4 py-4">
            <div>
                <p class="full-name">{{ request.user.get_full_name }}</p>
                <p class="font-weight-light date-join"><i class="far fa-calendar-alt"></i>  {{ request.user.get_date_joined }}</p>
            </div>
            {% if user.is_authenticated and user.id == request.user.id %}
                <button id="profile-edit-Btn" class="profile-edit-Btn">Chỉnh sửa hồ sơ</button>
            {% endif %}
        </div>
        <div class=" px-4 py-4 mt-3">
            <div>
                {% if user.is_authenticated and user.id == request.user.id %}
                <ul class="profile-vertical-menu">
                    <li><a href="{% url 'profile' user.get_full_name_link %}">Tin đăng của bạn</a></li>
                    
         
                    <hr>
                    <li class="active"><a href="{% url 'your_finance' %}">Ví của bạn</a></li>
                    <hr>
                    <li><a href="{% url 'post_saved' user.get_full_name_link %}">Đã lưu</a></li>
                </ul>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="profile-grid-item pl-1 pt-4 pr-5 pb-3">
        <div class="box shadow-sm px-4 py-4">
            <div>
                <ul class="profile-horizontal-menu">
                    <li data-section="in">Lịch sử nạp tiền</li>
                    <li data-section="out">Lịch sử đẩy tin</li>
                </ul>
            </div>
            <div class="d-flex">
                <div id="finance_now">Bạn đang có <span>{{ finance }}</span> đ</div>
                <a class="nav-link ml-auto" id="link-button-create_post" href="{% url 'view_form' %}">Đẩy tin</a>
            </div>
        </div>
        <div class="index-all-post pt-4">
        <div class="box  shadow-sm px-4 pb-4 mb-3">
            <!-- ĐANG ĐĂNG -->
            <!-- Bài đăng của người dùng đặt ở đây -->
            {% if his %}
            <div class="container pt-4">
                <table id="history">
                    <tr>
                        <th>Trạng thái</th>
                        <th>Mã code</th>
                        <th>Seri</th>
                        <th>Nhà mạng</th>
                        <th>Khai</th>
                        <th>Thực</th>
                        <th>Nhận</th>
                        <th>Ngày</th>
                        <th>Mã giao dịch</th>
                    </tr>
                    {% for h in his %}
                        <tr>
                            <td>
                                <span {{ h.is_waiting|yesno:' class=is_waiting,' }} {{ h.is_success|yesno:' class=is_success,' }} {{ h.is_fail|yesno:' class=is_fail,' }}>{{ h.get_status }}</span>
                            </td>
                            <td>{{ h.code }}</td>
                            <td>{{ h.serial }}</td>
                            <td>{{ h.telco }}</td>
                            <td>{{ h.declared_value }}</td>
                            <td>{{ h.value }}</td>
                            <td>{{ h.amount }}</td>
                            <td>{{ h.get_date }}</td>
                            <td>{{ h.request_id }}</td>
                        </tr>
                    {% empty %}
                    {% endfor %}
                </table>
            </div>
            {% else %}
            Bạn chưa có giao dịch nào
            {%  endif %}
        
        </div>
        </div>
    </div>
</div>

<div id="profile-edit-modal" class="modal">
    <div class="modal-content shadow-lg">
        <div class="modal-content-info">
            <div class="row motel-row-header">
                <div class="col-sm-8">
                    <div class="modal-content-header my-3">Chỉnh sửa hồ sơ của bạn</div>
                </div>
                <div class="col-sm-4">
                    <span class="close">&times;</span>
                </div>
            </div>
            <div class="row motel-row-body pt-4 px-3">
                <div class="col-sm-8 pr-4" id="motel-profile-form">
                    <form id="editProForm" action="{% url 'save_profile' %}" method="post" novalidate>
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-sm-6 mb-3">
                                <label for="last_name">Họ</label>
                                <input id="last_name"  name="last_name"  type="text" placeholder="Họ">
                            </div>
                            <div class="col-sm-6 mb-3">
                                <label for="first_name">Tên</label>
                                <input id="first_name" name="first_name" type="text" placeholder="Tên">
                            </div>
                        </div>
                        <div>
                            <label for="user_address">Địa chỉ</label>
                            <select name="address"  id="user_address">
                                <option  selected disabled hidden style='display: none' value="">Tỉnh</option>
                            </select>
                        </div>
    
                        <div class="mt-4"><input type="button"  id='editProBtn' value="Lưu"></div>
                        
                    </form>
                </div>
                <div class="col-sm-4">
                    <img src="{{MEDIA_URL}}/{{request.user.avatar}}" class="img-thumbnail mg-fluid rounded-circle" alt="Ảnh đại diện của bạn">
                </div>
            </div>
        </div>
    </div>
</div>

    
  
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

<script src="{% static 'motels/update_profile.js' %}"></script>
<script>
    document.addEventListener('DOMContentLoaded', () => {
        document.querySelector('.profile-horizontal-menu [data-section="in"]').className = 'active';
        
        convert(document.querySelector('#finance_now span').innerHTML, document.querySelector('#finance_now span'));
        document.querySelectorAll('.finance_each').forEach(td => {
            convert(td.innerHTML, td);
        })
    })

    function convert(amount, item) {
        let modun = parseInt(amount.length/3);
        let len = amount.length;
        let arr = new Array();
        for (let i = modun; i >= 0; i--) {
            arr[i] = ',' + amount.slice((len - (modun + 1-i)*3), (len-(modun-i)*3));
            if (i === 0) {
                arr[i] = amount.slice(0, len-modun*3);
            }
        } 
        let str = arr.toString();
        let str2 = str.replace(/,,/g,",");
        if (str2[0] === ',') {
            str2 = str2.slice(1, str2.length);
            item.innerHTML = str2;
        }
        else {
            item.innerHTML = str2;
        }
    }
</script>
{% endblock %}